image:
  name: atlassian/default-image:2

push: &push
  step:
    name: Push and Tag
    script:
      - ./ci-scripts/docker-release.sh sonarsource/$BITBUCKET_REPO_SLUG
      - ./ci-scripts/git-tag.sh
    services:
      - docker

pipelines:
  branches:
    master:
      - <<: *push
    qa-*:
      - <<: *push
    feature/*:
      - <<: *push
