image:
  name: atlassian/default-image:2

push: &push
  step:
    name: Push and Tag
    image: python:3.6.7
    script:
      - pip install semversioner==0.6.16
      - ./ci-scripts/bump-version.sh
      - ./ci-scripts/docker-release.sh sonarsource/$BITBUCKET_REPO_SLUG
      - ./ci-scripts/git-push.sh
    services:
      - docker

pipelines:
  custom:
    release:
      - <<: *push
